name: Build Code without Errors
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Run npm install
      run: npm install
    - name: Build Code
      run: |
        echo Building code,
        npm run-script build